version: '3.8'

services:
  nginx-conf:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - antarctic-app
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ~/dev/antarctic-front/dist/spa/:/quasar-app/
      - ./docker-compose.yml:/docker-compose.yml

networks:
  antarctic-app:
    driver: bridge
