version: '3.8'

services:
  nginx-conf:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ~/dev/antarctic-front/dist/spa/:/quasar-app/
